services:
  backend:
    build: ./backend
    container_name: docchat-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/data:/app/data  # garder les index FAISS persistants

  frontend:
    build: ./frontend
    container_name: docchat-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://localhost:8000
    depends_on:
      - backend
